/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   rest-apis-list-item.html
 */

/// <reference path="../polymer/types/polymer-element.d.ts" />
/// <reference path="../arc-icons/arc-icons.d.ts" />
/// <reference path="../iron-flex-layout/iron-flex-layout.d.ts" />
/// <reference path="../paper-styles/shadow.d.ts" />
/// <reference path="../paper-button/paper-button.d.ts" />
/// <reference path="../paper-menu-button/paper-menu-button.d.ts" />
/// <reference path="../paper-icon-button/paper-icon-button.d.ts" />
/// <reference path="../paper-listbox/paper-listbox.d.ts" />
/// <reference path="../paper-item/paper-item.d.ts" />
/// <reference path="../paper-item/paper-item-body.d.ts" />
/// <reference path="rest-apis-item-mixin.d.ts" />

declare namespace UiElements {

  /**
   * Displays a single list item for REST APIs list screen.
   *
   * ### Example
   *
   * ```html
   * <rest-apis-list-item item="{...}"></rest-apis-list-panel>
   * ```
   *
   * ### Styling
   * `<rest-apis-list-item>` provides the following custom properties and mixins for styling:
   *
   * Custom property | Description | Default
   * ----------------|-------------|----------
   * `--rest-apis-list-item` | Mixin applied to the element | `{}`
   * `--rest-apis-list-item-action-button` | Mixin applied to the visible accrion button | `{}`
   */
  class RestApisListItem extends
    ArcComponents.RestApisItemMixin(
    Object) {
  }
}

interface HTMLElementTagNameMap {
  "rest-apis-list-item": UiElements.RestApisListItem;
}
