/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   rest-apis-item-mixin.html
 */

/// <reference path="../polymer/types/lib/utils/mixin.d.ts" />

declare namespace ArcComponents {


  /**
   * Common function for rest APIs list items.
   */
  function RestApisItemMixin<T extends new (...args: any[]) => {}>(base: T): T & RestApisItemMixinConstructor;

  interface RestApisItemMixinConstructor {
    new(...args: any[]): RestApisItemMixin;
  }

  interface RestApisItemMixin {

    /**
     * REST API index datastore object
     */
    item: object|null|undefined;

    /**
     * If true, the element will not produce a ripple effect when interacted
     * with via the pointer.
     */
    noink: boolean|null|undefined;

    /**
     * Dispatches `open-list-item` so the panel can take an action.
     */
    requestOpen(): void;

    /**
     * Dispatches `delete-list-item` so the panel can take an action.
     */
    requestDelete(): void;
  }
}
